"use strict";

var CARTAS = [
    {
        id: 1,
        nombre: "Tom",
        serie: "Tom y Jerry",
        anio: 1940,
        creador: "William Hanna y Joseph Barbera",
        pais: "Estados Unidos",
        curiosidad: "La serie ganó varios premios Oscar por sus cortometrajes animados.",
        imagen: "assets/img/tom.png",
        parejaId: 2
    },
    {
        id: 2,
        nombre: "Jerry",
        serie: "Tom y Jerry",
        anio: 1940,
        creador: "William Hanna y Joseph Barbera",
        pais: "Estados Unidos",
        curiosidad: "La serie ganó varios premios Oscar por sus cortometrajes animados.",
        imagen: "assets/img/jerry.png",
        parejaId: 1
    },
    {
        id: 3,
        nombre: "Scooby-Doo",
        serie: "Scooby-Doo",
        anio: 1969,
        creador: "Joe Ruby y Ken Spears",
        pais: "Estados Unidos",
        curiosidad: "Es una de las franquicias animadas más longevas de Hanna-Barbera.",
        imagen: "assets/img/scooby-doo.png",
        parejaId: 4
    },
    {
        id: 4,
        nombre: "Shaggy",
        serie: "Scooby-Doo",
        anio: 1969,
        creador: "Joe Ruby y Ken Spears",
        pais: "Estados Unidos",
        curiosidad: "Es una de las franquicias animadas más longevas de Hanna-Barbera.",
        imagen: "assets/img/shaggy.png",
        parejaId: 3
    },
    {
        id: 5,
        nombre: "Bugs Bunny",
        serie: "Looney Tunes",
        anio: 1940,
        creador: "Warner Bros.",
        pais: "Estados Unidos",
        curiosidad: "Bugs Bunny es considerado la mascota oficial de Looney Tunes y uno de los personajes más famosos de la animación.",
        imagen: "assets/img/bugs-bunny.png",
        parejaId: 6
    },
    {
        id: 6,
        nombre: "Lola Bunny",
        serie: "Looney Tunes",
        anio: 1996,
        creador: "Warner Bros.",
        pais: "Estados Unidos",
        curiosidad: "Bugs Bunny es considerado la mascota oficial de Looney Tunes y uno de los personajes más famosos de la animación.",
        imagen: "assets/img/lola-bunny.png",
        parejaId: 5
    },
    {
        id: 7,
        nombre: "Pinky",
        serie: "Pinky y Cerebro",
        anio: 1995,
        creador: "Tom Ruegger",
        pais: "Estados Unidos",
        curiosidad: "Nació como segmento dentro de Animaniacs.",
        imagen: "assets/img/pinky.png",
        parejaId: 8
    },
    {
        id: 8,
        nombre: "Cerebro",
        serie: "Pinky y Cerebro",
        anio: 1995,
        creador: "Tom Ruegger",
        pais: "Estados Unidos",
        curiosidad: "Nació como segmento dentro de Animaniacs.",
        imagen: "assets/img/cerebro.png",
        parejaId: 7
    },
    {
        id: 9,
        nombre: "Bob Esponja",
        serie: "Bob Esponja",
        anio: 1999,
        creador: "Stephen Hillenburg",
        pais: "Estados Unidos",
        curiosidad: "Stephen Hillenburg era biólogo marino antes de crear Bob Esponja.",
        imagen: "assets/img/bob-esponja.png",
        parejaId: 10
    },
    {
        id: 10,
        nombre: "Patricio",
        serie: "Bob Esponja",
        anio: 1999,
        creador: "Stephen Hillenburg",
        pais: "Estados Unidos",
        curiosidad: "Stephen Hillenburg era biólogo marino antes de crear Bob Esponja.",
        imagen: "assets/img/patricio.png",
        parejaId: 9
    },
    {
        id: 11,
        nombre: "Mickey Mouse",
        serie: "Disney",
        anio: 1928,
        creador: "Walt Disney y Ub Iwerks",
        pais: "Estados Unidos",
        curiosidad: "Mickey debutó en Steamboat Willie en 1928.",
        imagen: "assets/img/mickey-mouse.png",
        parejaId: 12
    },
    {
        id: 12,
        nombre: "Minnie Mouse",
        serie: "Disney",
        anio: 1928,
        creador: "Walt Disney y Ub Iwerks",
        pais: "Estados Unidos",
        curiosidad: "Mickey debutó en Steamboat Willie en 1928.",
        imagen: "assets/img/minnie-mouse.png",
        parejaId: 11
    },
    {
        id: 13,
        nombre: "Pedro Picapiedra",
        serie: "Los Picapiedra",
        anio: 1960,
        creador: "William Hanna y Joseph Barbera",
        pais: "Estados Unidos",
        curiosidad: "Fue la primera serie animada emitida en horario central de televisión.",
        imagen: "assets/img/pedro-picapiedra.png",
        parejaId: 14
    },
    {
        id: 14,
        nombre: "Pablo Marmol",
        serie: "Los Picapiedra",
        anio: 1960,
        creador: "William Hanna y Joseph Barbera",
        pais: "Estados Unidos",
        curiosidad: "Fue la primera serie animada emitida en horario central de televisión.",
        imagen: "assets/img/pablo-marmol.png",
        parejaId: 13
    },
    {
        id: 15,
        nombre: "Dexter",
        serie: "Laboratorio de Dexter",
        anio: 1996,
        creador: "Genndy Tartakovsky",
        pais: "Estados Unidos",
        curiosidad: "Fue una de las series emblemáticas de Cartoon Network en los 90.",
        imagen: "assets/img/dexter.png",
        parejaId: 16
    },
    {
        id: 16,
        nombre: "Dee Dee",
        serie: "Laboratorio de Dexter",
        anio: 1996,
        creador: "Genndy Tartakovsky",
        pais: "Estados Unidos",
        curiosidad: "Fue una de las series emblemáticas de Cartoon Network en los 90.",
        imagen: "assets/img/dee-dee.png",
        parejaId: 15
    },
    {
        id: 17,
        nombre: "Arnold",
        serie: "Hey Arnold!",
        anio: 1996,
        creador: "Craig Bartlett",
        pais: "Estados Unidos",
        curiosidad: "Está ambientada en una ciudad ficticia inspirada en Nueva York y Seattle.",
        imagen: "assets/img/arnold.png",
        parejaId: 18
    },
    {
        id: 18,
        nombre: "Helga",
        serie: "Hey Arnold!",
        anio: 1996,
        creador: "Craig Bartlett",
        pais: "Estados Unidos",
        curiosidad: "Está ambientada en una ciudad ficticia inspirada en Nueva York y Seattle.",
        imagen: "assets/img/helga.png",
        parejaId: 17
    },
    {
        id: 19,
        nombre: "Garfield",
        serie: "Garfield",
        anio: 1978,
        creador: "Jim Davis",
        pais: "Estados Unidos",
        curiosidad: "Garfield apareció originalmente como tira cómica en 1978.",
        imagen: "assets/img/garfield.png",
        parejaId: 20
    },
    {
        id: 20,
        nombre: "Odie",
        serie: "Garfield",
        anio: 1978,
        creador: "Jim Davis",
        pais: "Estados Unidos",
        curiosidad: "Garfield apareció originalmente como tira cómica en 1978.",
        imagen: "assets/img/odie.png",
        parejaId: 19
    },
    {
        id: 21,
        nombre: "Inspector Gadget",
        serie: "Inspector Gadget",
        anio: 1983,
        creador: "Andy Heyward, Jean Chalopin y Bruno Bianchi",
        pais: "Estados Unidos / Francia / Canadá",
        curiosidad: "Fue una de las primeras series animadas ampliamente generadas por computadora para producción televisiva.",
        imagen: "assets/img/inspector-gadget.png",
        parejaId: 22
    },
    {
        id: 22,
        nombre: "Penny",
        serie: "Inspector Gadget",
        anio: 1983,
        creador: "Andy Heyward, Jean Chalopin y Bruno Bianchi",
        pais: "Estados Unidos / Francia / Canadá",
        curiosidad: "Fue una de las primeras series animadas ampliamente generadas por computadora para producción televisiva.",
        imagen: "assets/img/penny.png",
        parejaId: 21
    },
    {
        id: 23,
        nombre: "Lion-O",
        serie: "Thundercats",
        anio: 1985,
        creador: "Ted Wolf",
        pais: "Estados Unidos",
        curiosidad: "La animación fue producida por un estudio japonés.",
        imagen: "assets/img/lion-o.png",
        parejaId: 24
    },
    {
        id: 24,
        nombre: "Panthro",
        serie: "Thundercats",
        anio: 1985,
        creador: "Ted Wolf",
        pais: "Estados Unidos",
        curiosidad: "La animación fue producida por un estudio japonés.",
        imagen: "assets/img/panthro.png",
        parejaId: 23
    },
    {
        id: 25,
        nombre: "Rayo de Plata",
        serie: "Halcones Galacticos",
        anio: 1986,
        creador: "Arthur Rankin Jr. y Jules Bass",
        pais: "Estados Unidos",
        curiosidad: "Comparte equipo creativo con Thundercats.",
        imagen: "assets/img/rayo-de-plata.png",
        parejaId: 26
    },
    {
        id: 26,
        nombre: "Acerina",
        serie: "Halcones Galacticos",
        anio: 1986,
        creador: "Arthur Rankin Jr. y Jules Bass",
        pais: "Estados Unidos",
        curiosidad: "Comparte equipo creativo con Thundercats.",
        imagen: "assets/img/acerina.png",
        parejaId: 25
    },
    {
        id: 27,
        nombre: "He-Man",
        serie: "He-Man",
        anio: 1983,
        creador: "Lou Scheimer",
        pais: "Estados Unidos",
        curiosidad: "Fue creado para promocionar la línea de juguetes Masters of the Universe.",
        imagen: "assets/img/he-man.png",
        parejaId: 28
    },
    {
        id: 28,
        nombre: "Teela",
        serie: "He-Man",
        anio: 1983,
        creador: "Lou Scheimer",
        pais: "Estados Unidos",
        curiosidad: "Fue creado para promocionar la línea de juguetes Masters of the Universe.",
        imagen: "assets/img/teela.png",
        parejaId: 27
    },
    {
        id: 29,
        nombre: "Leonardo",
        serie: "Tortugas Ninja",
        anio: 1987,
        creador: "Kevin Eastman y Peter Laird",
        pais: "Estados Unidos",
        curiosidad: "Comenzaron como un cómic independiente antes de convertirse en fenómeno mundial.",
        imagen: "assets/img/leonardo.png",
        parejaId: 30
    },
    {
        id: 30,
        nombre: "Raphael",
        serie: "Tortugas Ninja",
        anio: 1987,
        creador: "Kevin Eastman y Peter Laird",
        pais: "Estados Unidos",
        curiosidad: "Comenzaron como un cómic independiente antes de convertirse en fenómeno mundial.",
        imagen: "assets/img/raphael.png",
        parejaId: 29
    },
    {
        id: 31,
        nombre: "Optimus Prime",
        serie: "Transformers",
        anio: 1984,
        creador: "Hasbro y Takara",
        pais: "Estados Unidos / Japón",
        curiosidad: "La franquicia nació a partir de una línea de juguetes transformables.",
        imagen: "assets/img/optimus-prime.png",
        parejaId: 32
    },
    {
        id: 32,
        nombre: "Bumblebee",
        serie: "Transformers",
        anio: 1984,
        creador: "Hasbro y Takara",
        pais: "Estados Unidos / Japón",
        curiosidad: "La franquicia nació a partir de una línea de juguetes transformables.",
        imagen: "assets/img/bumblebee.png",
        parejaId: 31
    },
    {
        id: 33,
        nombre: "Goku",
        serie: "Dragon Ball Z",
        anio: 1989,
        creador: "Akira Toriyama",
        pais: "Japón",
        curiosidad: "Es una de las series de anime más populares de todos los tiempos.",
        imagen: "assets/img/goku.png",
        parejaId: 34
    },
    {
        id: 34,
        nombre: "Vegeta",
        serie: "Dragon Ball Z",
        anio: 1989,
        creador: "Akira Toriyama",
        pais: "Japón",
        curiosidad: "Es una de las series de anime más populares de todos los tiempos.",
        imagen: "assets/img/vegeta.png",
        parejaId: 33
    },
    {
        id: 35,
        nombre: "Correcaminos",
        serie: "Looney Tunes",
        anio: 1949,
        creador: "Chuck Jones",
        pais: "Estados Unidos",
        curiosidad: "Chuck Jones estableció reglas estrictas: el Correcaminos nunca podía atacar al Coyote y el Coyote siempre fracasaba por sus propios planes.",
        imagen: "assets/img/correcaminos.png",
        parejaId: 36
    },
    {
        id: 36,
        nombre: "El Coyote",
        serie: "Looney Tunes",
        anio: 1949,
        creador: "Chuck Jones",
        pais: "Estados Unidos",
        curiosidad: "Chuck Jones estableció reglas estrictas: el Correcaminos nunca podía atacar al Coyote y el Coyote siempre fracasaba por sus propios planes.",
        imagen: "assets/img/coyote.png",
        parejaId: 35
    }
];